# Sử dụng Node.js base image
FROM node:20-alpine

# Tạo thư mục trong container
WORKDIR /app

# Copy file cấu hình vào container
COPY package*.json ./

# Cài dependencies
RUN npm install

# Copy toàn bộ mã nguồn vào container
COPY . .

# Expose cổng mà app chạy (8081)
EXPOSE 8081

# Lệnh chạy ứng dụng
CMD ["node", "index.js"]